- practicas/1/FranciscoRodrigo/rodrigo.txt
> Agrego el nombre de Rodrigo Francisco

- practicas/1/GarciaVicente/vicente.txt
Seguí los pasos de la práctica 1, cree un fork, clone el repositorio y en practicas cree la carpeta "1" y en ella otra con el nombre de "GarciaVicente" y en ella un archivo txt con mi nombre.
> Agrego el nombre de Vicente Garcia

- practicas/1/GuerreroEnrique/EnriqueGuerreroL.txt
> Agrego el nombre de Enrique Guerrero Lopez

- practicas/1/GonzalezFelix/Felix.txt
Anexe archico de la practica 1 con mi nombre y nombre de usuario.
> Agrego el nombre de Felix Gonzalez

- practicas/1/DuránArturo/arturoaccess.txt
Creacion del archivo .txt con el nombre de usuario y nombre real.
> Agrego el nombre de José Arturo Durán Romero

- practicas/1/AguileraErnesto/Ernesto.txt
Agrego mi información de contacto
> Practica 1

- practicas/1/RodriguezZuriel/nowhereknight.txt
> Agrego el nombre de Rodríguez Agiss Zuriel Uzai

- practicas/1/RomeroVicente/ValdrST.txt
> Agrego el nombre de Vicente Romero Andrade

- practicas/1/MataLuis/luismata.txt
Agrego mi practica 1. Luis Mata Mota
> Agrego el nombre de Luis Mata

- practicas/2/SanchezBeatriz/B/pract2B.txt
> Agrego el archivo de Beatriz Sanchez para la práctica 2B

- practicas/2/MoralesCarlos/B/cpuinfo.txt
Agrego el archivo de Morales Carlos para la práctica 2B
> Agrego el archivo de Morales Carlos para la práctica 2B

- practicas/2/PerezRuizMiguel/B/cpuinfo.txt
> Practica2b

- practicas/1/LeonardoGonzalez/LeoAlonsoGonzalez.txt
borre el archivo que estaba duplicado ya que me equivoque en el nombre del directorio y no lo habia eliminado correctamente
> Borre el archivo duplicado

- practicas/2/GuerreroEnrique/B/practica2b.txt
Agrego archivo de la práctica 2B.
> Agrego el archivo de Enrique Guerrero para la practica 2B

- practicas/2/GonzalezLeonardo/B/cpuinfo.txt
> Agrego el archivo de Leonardo Gonzalez para la práctica 2B

- practicas/2/PérezQuirozMiguel/B/saludo.txt
Se incluye un archivo con un hola mundo
> Agrego el archivo de PérezQuirozMiguel para la práctica 2B

- practicas/2/DuránArturo/B/cpuinfo.txt
> Agrego el archivo de Arturo Durán para la práctica 2B

- tareas/2/AguileraErnesto/Balsa.py
No funciona :/ , espero poder corregirla en unos días.
> Agrego tarea 2 de Ernesto Aguilera, no sirve en esta version

- tareas/2/Gonzalez Felix - Guzman Yared/El cruce del rio.py
> Agrego el archivo Gonzalez Felix - Yared Guzman tarea2

- practicas/3/AguilarGabriel/.gitignore
- practicas/3/AguilarGabriel/productoParalelo.c
El contenido del archivo .gitignore es 'productoParalelo' porque al compilar indique con la opción -o ese nombre para el archivo compilado.
> Practica3 Gabriel Aguilar

- practicas/3/PerezQuirozMiguel/.gitignore
- practicas/3/PerezQuirozMiguel/hola.c
> Se agrega práctica 3

- practicas/3/GuerreroEnrique/.gitignore
- practicas/3/GuerreroEnrique/hola.c
> Práctica 3

- tareas/3/MataLuis/fifo.py
- tareas/3/MataLuis/ronda1.py
- tareas/3/MataLuis/ronda4.py
Agrego archivos de la tarea 3.
Se que es tarde pero no me lograban salir, deecho aun no estoy seguro de que esten del todo bien.
> Agrego archivos de la tarea 3, un poco tarde

- tareas/3/EspinozaAlberto/tarea3.cpp
> agrego tarea 3

- tareas/3/GarciaVicente-GuerreroEnrique/ProgramaT3.py
Archivo para la tarea 3. Solución bastante apresurada y no elegante.
> Agrego programa-monstruo para la tarea 3

- proyectos/2/MataLuis/banco.py
- proyectos/2/MataLuis/proyecto2Documentacion
Mata Mota Luis Valentin 
Simulación de la espera en una caja de un banco.
> Agrego archivos del segundo proyecto

- proyectos/3/MataLuis/proyecto.py
Agrego proyecto de Luis Mata 
El peor error que eh cometido en mi vida es querer subirlo por partes, se rompio mi programa y ya no supe que movi, por lo que esta incompleto. 
Saludos profesor. Nos vemos el Martes
> Proyecto3 de Luis Mata

- proyectos/3/AguileraErnesto/System.py
Su clase fue genial, aunque varias veces me quedé con ganas de que sus programas ejemplo corrieran :). Espero no irme a final jajajaja, ojalá diera compiladores o redes.
> Proyecto 3

- proyectos/3/GarciaOrlando-RodriguezZuriel/Documentacion
- proyectos/3/GarciaOrlando-RodriguezZuriel/FIFS.py
Antes de ejecutar indicar en la fs_image  la imagen a trabajar o solo dejar asi. 
Mi internet se demoro demasiado
> Proyecto3 Orlando-ZUriel
